//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkCrud_02_05_2017
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string email { get; set; }
    }
}
